# Generated by Django 2.2.8 on 2020-10-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brands/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GROUPES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Régions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
            ],
            options={
                'verbose_name_plural': 'Magasins',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HYP', models.BooleanField(default=False)),
                ('SUP', models.BooleanField(default=False)),
                ('MINI', models.BooleanField(default=False)),
                ('CODE', models.CharField(default='', max_length=200)),
                ('DESIGNATION', models.CharField(default='', max_length=200)),
                ('DESCRIPTION', models.TextField(default='')),
                ('PCB', models.IntegerField(default=0)),
                ('GENCODE', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='Products/')),
                ('date', models.DateField(auto_now_add=True)),
                ('CATEGORIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('GROUPE_PRODUIT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GROUPES')),
            ],
            options={
                'verbose_name_plural': 'Produit',
                'ordering': ['-date'],
            },
        ),
    ]
