# Generated by Django 2.2.8 on 2020-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='NAME',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='amt',
        ),
        migrations.AddField(
            model_name='product',
            name='INGREDIENTS',
            field=models.ManyToManyField(blank=True, null=True, to='core.Ingredient'),
        ),
    ]
