# Generated by Django 2.2.8 on 2020-10-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201010_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-date'], 'verbose_name_plural': '08. Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date'], 'verbose_name_plural': '07. CATEGORIES'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date'], 'verbose_name_plural': '03. CONTACTS'},
        ),
        migrations.AlterModelOptions(
            name='groupes',
            options={'verbose_name_plural': '06. GROUPES'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': '05. INGREDIENTS'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name_plural': '01. PRODUITS'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-date'], 'verbose_name_plural': '04. Régions'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-date'], 'verbose_name_plural': '02. MAGASINS'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='IMAGE',
        ),
        migrations.AddField(
            model_name='product',
            name='BRAND',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='SIZE',
            field=models.CharField(default='', max_length=100),
        ),
    ]
