# Generated by Django 2.2.8 on 2020-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pdfrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='REQUEST_INFO',
            field=models.BooleanField(default=False),
        ),
    ]
