# Generated by Django 2.2.8 on 2020-10-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201010_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-date'], 'verbose_name_plural': '08. MARQUES'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='INGREDIENTS',
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(default='', max_length=100)),
                ('INGREDIENTS', models.ManyToManyField(to='core.Ingredient')),
            ],
            options={
                'verbose_name_plural': '09. INGREDIENTS LIST',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='INGREDIENTS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.IngredientList'),
        ),
    ]
