# Generated by Django 2.2.8 on 2020-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201108_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='Fax',
            field=models.CharField(default='+590 (0) 590 26 73 20', max_length=100),
        ),
    ]
