# Generated by Django 2.2.8 on 2020-10-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201011_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(default='', max_length=200)),
                ('PRODUIT', models.CharField(default='', max_length=200)),
                ('PARTICULARITE', models.CharField(default='', max_length=200)),
                ('IMAGE', models.ImageField(default='default.jpg', upload_to='HomePage/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '8. YOUR HOME SCREEN',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-date'], 'verbose_name_plural': '6. MARQUES'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date'], 'verbose_name_plural': '5. CATEGORIES'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date'], 'verbose_name_plural': '3. CONTACTS'},
        ),
        migrations.AlterModelOptions(
            name='groupes',
            options={'verbose_name_plural': '4. GROUPES'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': '9. INGREDIENTS'},
        ),
        migrations.AlterModelOptions(
            name='ingredientlist',
            options={'verbose_name_plural': '7. INGREDIENTS LIST'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['DESIGNATION'], 'verbose_name_plural': '1. PRODUITS'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-date'], 'verbose_name_plural': '8. Régions'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-date'], 'verbose_name_plural': '2. MAGASINS'},
        ),
    ]
