# Generated by Django 2.2.8 on 2020-11-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201130_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='IMG1',
            field=models.ImageField(default='default.jpg', upload_to='HomePage/'),
        ),
        migrations.AddField(
            model_name='utility',
            name='IMG2',
            field=models.ImageField(default='default.jpg', upload_to='HomePage/'),
        ),
        migrations.AddField(
            model_name='utility',
            name='IMG3',
            field=models.ImageField(default='default.jpg', upload_to='HomePage/'),
        ),
    ]
